-- ============================================================================
-- Ryuma - v41: Event / กิจกรรม system ("พรีครบ N รายการ รับคูปอง").
-- Paste into the Supabase SQL Editor. Safe to re-run (idempotent).
--
-- Adds two tables (campaigns, campaign_awards) + a campaign_id tag column on
-- coupons (so reward coupons auto-generated by an event are hidden from the
-- coupon manager). Rewards are minted in the ADMIN session at order approval,
-- so the write policies below are admin-only for grants/awards -- customers
-- never self-mint (same safety model as coupons, ryuma-dna-save).
--
-- Depends on v20/v21/v33 helpers: app_user_id(), is_app_admin(), is_app_approved().
-- ============================================================================

-- 1. Event templates
create table if not exists campaigns (
  id text primary key,
  name text not null,
  banner_url text,
  product_blurb text,
  starts_at text not null,           -- 'YYYY-MM-DD' (inclusive, from start of day)
  ends_at text not null,             -- 'YYYY-MM-DD' (inclusive, to end of day)
  active boolean not null default true,
  tiers jsonb not null default '[]'::jsonb,   -- [{threshold, coupon_value, coupon_count}, ...]
  reward_scope text not null default 'both',  -- preorder | instock | both
  reward_expiry_days int not null default 30, -- reward coupon expires this many days after grant
  target_maker_id text,
  target_product_id text,
  created_at timestamptz not null default now()
);

-- 2. One row per reward already GRANTED to a user (campaign tier at a loop cycle).
--    Its existence = "already granted", so a reward can never be double-issued;
--    a later loop cycle is a different (tier_index, cycle) key so repeats still qualify.
create table if not exists campaign_awards (
  id text primary key,
  campaign_id text not null references campaigns(id) on delete cascade,
  user_id text not null references users(id) on delete cascade,
  tier_index int not null,              -- stores the tier THRESHOLD (stable across tier edits), not an array index
  cycle int not null,
  claimed_at timestamptz not null default now(),
  coupon_id text
);
create index if not exists campaign_awards_user_idx on campaign_awards(user_id);
create index if not exists campaign_awards_campaign_idx on campaign_awards(campaign_id);

-- 3. tag column so reward coupons can be filtered out of the coupon manager
alter table coupons add column if not exists campaign_id text;

-- 4. RLS
alter table campaigns enable row level security;
alter table campaign_awards enable row level security;

-- campaigns: any approved member (or admin) can read the running event; only admin writes.
drop policy if exists campaigns_read on campaigns;
create policy campaigns_read on campaigns for select
  using (is_app_approved() or is_app_admin());

drop policy if exists campaigns_admin on campaigns;
create policy campaigns_admin on campaigns for all
  using (is_app_admin()) with check (is_app_admin());

-- campaign_awards: a member sees their OWN; only admin inserts/updates/deletes
-- (rewards are granted in the admin session at order approval).
drop policy if exists campaign_awards_read on campaign_awards;
create policy campaign_awards_read on campaign_awards for select
  using (user_id = app_user_id() or is_app_admin());

drop policy if exists campaign_awards_write on campaign_awards;
create policy campaign_awards_write on campaign_awards for all
  using (is_app_admin()) with check (is_app_admin());

-- self-check (optional):
-- select polname, cmd from pg_policies where tablename in ('campaigns','campaign_awards');
-- select column_name from information_schema.columns where table_name='campaigns';
